version: "3.1"
services:
    nginx:
        image: 057731636091.dkr.ecr.us-east-1.amazonaws.com/bookstore-docker-nginx
        restart: always
        build:
            context: ./nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
    app:
        restart: always
        build: 
            context: .
        image: 057731636091.dkr.ecr.us-east-1.amazonaws.com/bookstore-docker-app
        expose:
        - "8080"